apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodejsapis.example.api.com
spec:
  group: example.api.com
  names:
    kind: NodejsAPI
    listKind: NodejsAPIList
    plural: nodejsapis
    singular: nodejsapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
