---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: sharp-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nodejs
  template:
    metadata:
      labels:
        name: nodejs
    spec:
      serviceAccountName: nodejs
      containers:
        - name: nodejs
          # Replace this with the built image name
          image: "quay.io/superlamer/nodejs-operator"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nodejs"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
      volumes:
        - name: runner
          emptyDir: {}
