kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodejs
  namespace: sharp-nonprod
subjects:
- kind: ServiceAccount
  name: nodejs
roleRef:
  kind: Role
  name: nodejs
  apiGroup: rbac.authorization.k8s.io
